ARG SRC_IMAGE=ghcr.io/jahia/jahia-docker-mvn-cache:11-jdk-noble-node-base
ARG CACHE_IMAGE=ghcr.io/jahia/jahia-docker-mvn-cache:17-jdk-noble-mvn-loaded

FROM $CACHE_IMAGE AS cache

FROM $SRC_IMAGE
LABEL maintainer="Jahia"

COPY --from=cache /root/.m2 /root/.m2
