name: On Code Change

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

env:
  DEFAULT_VERSION: 17-jdk-alpine

jobs:
  # Builds a base image containing the maven cache
  build-base:
    name: Buid and push Base docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
            ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Base image
        uses: docker/build-push-action@v6
        with:
          ssh: default
          push: true
          file: ./Dockerfile-base
          tags: ghcr.io/jahia/jahia-docker-mvn-cache:${{ env.DEFAULT_VERSION }}-node-base
          build-args: |
            BASE_TAG=${{ env.DEFAULT_VERSION }}

      - name: Build and push Loaded image
        uses: docker/build-push-action@v6
        with:
          ssh: default
          push: true
          file: ./Dockerfile
          tags: ghcr.io/jahia/jahia-docker-mvn-cache:${{ env.DEFAULT_VERSION }}-mvn-loaded
          build-args: |
            SRC_IMAGE=ghcr.io/jahia/jahia-docker-mvn-cache:${{ env.DEFAULT_VERSION }}-node-base

  build-additional:
    name: Build and push Additional docker images
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version:
          - "8-jdk-alpine"
          - "11-jdk-alpine"
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.BASTION_SSH_PRIVATE_KEY_JAHIACI }}
            ${{ secrets.GH_SSH_PRIVATE_KEY_JAHIACI }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Base image
        uses: docker/build-push-action@v6
        with:
          ssh: default
          push: true
          file: ./Dockerfile-base
          tags: ghcr.io/jahia/jahia-docker-mvn-cache:${{ matrix.jdk_version }}-node-base

      - name: Build and push Loaded image USING CACHE
        uses: docker/build-push-action@v6
        with:
          ssh: default
          push: true
          file: ./Dockerfile-fromcache
          tags: ghcr.io/jahia/jahia-docker-mvn-cache:${{ matrix.jdk_version }}-mvn-loaded
          build-args: |
            SRC_IMAGE=ghcr.io/jahia/jahia-docker-mvn-cache:${{ matrix.jdk_version }}-node-base          
            CACHE_IMAGE=ghcr.io/jahia/jahia-docker-mvn-cache:${{ env.DEFAULT_VERSION }}-mvn-loaded
